version: "3.1"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"

    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=PlanetariumDB
      - POSTGRES_USER=startramp
      - POSTGRES_PASSWORD=Yfhvfnjr66

    depends_on:
      - db



  db:
    image: postgres:14-alpine3.14
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=PlanetariumDB
      - POSTGRES_USER=startramp
      - POSTGRES_PASSWORD=Yfhvfnjr66
