# Generated by Django 4.2.4 on 2023-08-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="planetariumdome",
            name="address",
            field=models.CharField(default=None, max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="planetariumdome",
            name="city_state_province",
            field=models.CharField(default=None, max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="planetariumdome",
            name="country",
            field=models.CharField(default=None, max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="planetariumdome",
            name="dome_size",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="planetariumdome",
            name="phone",
            field=models.CharField(default=None, max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="planetariumdome",
            name="website",
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
