# Generated by Django 4.2.4 on 2023-08-15 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0003_planetariumdome_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planetariumdome",
            name="dome_size",
        ),
    ]
