# Generated by Django 4.2.4 on 2023-08-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0007_alter_planetariumdome_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planetariumdome",
            name="website",
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
